"""Add Complaint, StatusHistory, Attachment, and ResolutionReport models

Revision ID: a7de7b925acb
Revises: 25a8edda8b9f
Create Date: 2026-07-04 15:04:58.889663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7de7b925acb'
down_revision: Union[str, Sequence[str], None] = '25a8edda8b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('municipality_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('location_name', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geo_point', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['complaint_categories.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_municipality_id'), ['municipality_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_user_id'), ['user_id'], unique=False)

    op.create_table('complaint_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('storage_provider', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('public_url', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('upload_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_attachments_complaint_id'), ['complaint_id'], unique=False)

    op.create_table('complaint_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_status_history_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_status_history_created_at'), ['created_at'], unique=False)

    op.create_table('resolution_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('officer_name', sa.String(length=255), nullable=False),
    sa.Column('actions', sa.Text(), nullable=False),
    sa.Column('citizen_remarks', sa.Text(), nullable=True),
    sa.Column('before_image_url', sa.String(length=1024), nullable=True),
    sa.Column('after_image_url', sa.String(length=1024), nullable=True),
    sa.Column('date_resolved', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resolution_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolution_reports_complaint_id'), ['complaint_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resolution_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolution_reports_complaint_id'))

    op.drop_table('resolution_reports')
    with op.batch_alter_table('complaint_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_status_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaint_status_history_complaint_id'))

    op.drop_table('complaint_status_history')
    with op.batch_alter_table('complaint_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_attachments_complaint_id'))

    op.drop_table('complaint_attachments')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_user_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_municipality_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_category_id'))

    op.drop_table('complaints')
    # ### end Alembic commands ###
